services:

  postgres:
    image: postgres:16
    container_name: claimos_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: claimos_fraud

    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: claimos_redis

    ports:
      - "6379:6379"

  neo4j:
    image: neo4j:5
    container_name: claimos_neo4j

    environment:
      NEO4J_AUTH: neo4j/password

    ports:
      - "7474:7474"
      - "7687:7687"